// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcTsIB-h-rY3Ba04asYnLpqmZIjES2GmA',
    appId: '1:739403234657:web:9d74c3213a99ee74b35920',
    messagingSenderId: '739403234657',
    projectId: 'beautyapp-d64af',
    authDomain: 'beautyapp-d64af.firebaseapp.com',
    storageBucket: 'beautyapp-d64af.appspot.com',
    measurementId: 'G-2CR8C2PFVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgAyYegOleLN9-ekZtzcdTBKkFPxKNmF4',
    appId: '1:739403234657:android:4d644fa2cd5a6f4cb35920',
    messagingSenderId: '739403234657',
    projectId: 'beautyapp-d64af',
    storageBucket: 'beautyapp-d64af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeRM2bEOLU-pIxK0muVr_Iun3_DsfovIo',
    appId: '1:739403234657:ios:0aa5083f1bf367d8b35920',
    messagingSenderId: '739403234657',
    projectId: 'beautyapp-d64af',
    storageBucket: 'beautyapp-d64af.appspot.com',
    iosBundleId: 'com.example.beautyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeRM2bEOLU-pIxK0muVr_Iun3_DsfovIo',
    appId: '1:739403234657:ios:0aa5083f1bf367d8b35920',
    messagingSenderId: '739403234657',
    projectId: 'beautyapp-d64af',
    storageBucket: 'beautyapp-d64af.appspot.com',
    iosBundleId: 'com.example.beautyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcTsIB-h-rY3Ba04asYnLpqmZIjES2GmA',
    appId: '1:739403234657:web:faf64de0fe0a3416b35920',
    messagingSenderId: '739403234657',
    projectId: 'beautyapp-d64af',
    authDomain: 'beautyapp-d64af.firebaseapp.com',
    storageBucket: 'beautyapp-d64af.appspot.com',
    measurementId: 'G-5FC7MQZFEV',
  );
}
